### ISSUE TITLE
将服务端部署在有公网IP的服务器上后连接失败

### ISSUE THREAD

**Issue by py-162157** [jarryleo/watch_together#2]
作者你好，我在有公网IP的服务器上部署了服务端，用ufw确保了51127端口是开放的，也在项目里修改了服务器IP并重新编译了，但是始终连接失败。如果在本地运行的虚拟机上运行服务端的话，却可以正常连接至该服务器。
请问作者，在云服务器上部署服务端是否还有一些额外的步骤呢？

**Comment by jarryleo** [comment]
除了开启端口外，还要在防火墙放行，还要在云服务器后台启用规则等。这个项目我也没有做宣传推广，有什么bug欢迎反馈哈。

**Comment by py-162157** [comment]
成功了，原来是没有在控制端设置防火墙放行，谢谢你贡献的项目！

**Comment by xsgteamx** [comment]
> 作者你好，我在有公网IP的服务器上部署了服务端，用ufw确保了51127端口是开放的，也在项目里修改了服务器IP并重新编译了，但是始终连接失败。如果在本地运行的虚拟机上运行服务端的话，却可以正常连接至该服务器。 请问作者，在云服务器上部署服务端是否还有一些额外的步骤呢？

---

非常感谢你们提供的帮助,我用用看!!!
