### ISSUE TITLE
创建房间时，joinMulticast 会提示Invalid argument错误，试了iOS和android都会

### ISSUE THREAD

**Issue by luckmlc** [jarryleo/watch_together#4]
代码：

_socketServer!.joinMulticast(_UPNP_AddressIPv4);

报错内容：

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: OS Error: Invalid argument, errno = 22
#0      _NativeSocket.nativeJoinMulticast (dart:io-patch/socket_patch.dart:1791:68)
#1      _NativeSocket.joinMulticast (dart:io-patch/socket_patch.dart:1710:5)
#2      _RawDatagramSocket.joinMulticast (dart:io-patch/socket_patch.dart:2587:13)
#3      _ServerListen.start (package:watch_together/dlna/dlna_flutter.dart:1185:20)

**Comment by jarryleo** [comment]
是什么原因导致的呢。你自己关闭了问题，是找到解决方案了吗？我最近找到一个免费的mqtt服务，打算改成mqtt的，这样就不用自己部署服务器了。
